# Generated by Django 4.2.9 on 2024-01-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='table',
            field=models.TextField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='popularity',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='popularity',
            name='table',
            field=models.FileField(null=True, upload_to='', verbose_name='Таблица'),
        ),
    ]
