# Generated by Django 4.2.9 on 2024-01-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_alter_geography_image_alter_geography_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='popularity',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles', verbose_name='Изображение'),
        ),
    ]
