# Generated by Django 4.2.9 on 2024-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0006_alter_geography_image_alter_geography_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='staticfiles/skills/graphs', verbose_name='Изображение')),
                ('table', models.FileField(null=True, upload_to='staticfiles/skills/tables', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
                'db_table': 'prof-Skills',
            },
        ),
    ]
