# Generated by Django 4.2.9 on 2024-01-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0007_profskills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profskills',
            options={'verbose_name': 'Навыки по профессии', 'verbose_name_plural': 'Навыки по профессии'},
        ),
    ]
